name: Version Tag Creator

on:
  push:
    branches: [ main ]
    paths: [ 'package.json' ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch current and previous commit
          
      - name: Check if version changed
        id: version-check
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Get previous version from the parent commit
          git show HEAD~1:package.json > previous-package.json
          PREVIOUS_VERSION=$(jq -r '.version' previous-package.json)
          echo "previous_version=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT
          
          # Check if version changed
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged: $CURRENT_VERSION"
          fi
          
      - name: Create tag
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          VERSION=${{ steps.version-check.outputs.current_version }}
          TAG_NAME="v$VERSION"
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if tag already exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists"
            exit 0
          fi
          
          # Create and push tag
          git tag -a "$TAG_NAME" -m "Release version $VERSION"
          git push origin "$TAG_NAME"
          
          echo "Created and pushed tag: $TAG_NAME"